bin/stud-{ssh,vnc}: cleanup

diff --git a/bin/uni-vnc b/bin/uni-vnc
--- a/bin/uni-vnc
+++ b/bin/uni-vnc
@@ -2,15 +2,21 @@
 
 # TODO: race-free solution instead of freeport freedisp
 # TODO: file bug to openssh: `-f` doesn't work together with `-S`
+#       when that is fixed, remove the sleep workarounds
 # TODO: alternative to `x11vnc -storepasswd` and copy, it has version incompatibilities
+#       somehow non-reproducable?
 
 set -e
 
-SSHCS="~/.ssh/control:%h:%p:%r"
-LOCALVNCPW="/home/stev47/.vnc/stud-vnc-passwd"
-REMOTEVNCPW="/home/2011/hilbsn/.vnc/stud-vnc-passwd"
 
-HOST=hilbsn@${1}.mathematik.uni-stuttgart.de
+USER="hilbsn"
+SSHCS="~/.ssh/control:%h:%p:%r"
+# needs to be without quotes or else `readlink -f` fails?
+LOCALVNCPW=~/.vnc/stud-vnc-passwd
+# needs to be with quotes to prevent local tilde expansion
+REMOTEVNCPW="~/.vnc/stud-vnc-passwd"
+
+HOST=${USER}@${1}.mathematik.uni-stuttgart.de
 
 freeport () {
   NUM=5900
@@ -27,7 +33,6 @@ freedisp () {
   done
   echo :$NUM
 }
-
 
 # generate password token (vnc passwd truncates to 8 chars)
 PW=`cat /dev/urandom | base64 | fold -w 8 | head -n 1`
@@ -49,6 +54,9 @@ echo "starting remote Xvfb ..."
 ssh -S $SSHCS $HOST "Xvfb $VNCDISPLAY -nolisten tcp -screen 0 ${DISPLAYSIZE}x16" &
 
 echo "preparing password file ..."
+# stupid path expansion needed for local and remote
+LOCALVNCPW=$(readlink -f $LOCALVNCPW)
+REMOTEVNCPW=$(ssh -S $SSHCS $HOST "readlink -f $REMOTEVNCPW && true")
 echo -n $(ssh -S $SSHCS $HOST "x11vnc -storepasswd $PW $REMOTEVNCPW && cat $REMOTEVNCPW") > $LOCALVNCPW
 
 echo "starting remote x11vnc ..."
@@ -62,6 +70,6 @@ echo "starting vncviewer ..."
 vncviewer -passwd $LOCALVNCPW localhost:$LOCALPORT
 
 echo "cleaning up ..."
-ssh -S $SSHCS $HOST "killall Xvfb x11vnc || true"
+ssh -S $SSHCS $HOST "killall -u $USER Xvfb x11vnc || true"
 ssh -S $SSHCS -O exit $HOST
 
